/**
 * Route Export — Generate navigation app links + GPX files
 * 
 * Supports:
 * - Apple Maps URL (maps:// scheme with waypoints)
 * - Google Maps URL (via waypoints)
 * - GPX file download (universal)
 */

import type { ScoredRoute } from '../types/route'

/**
 * Sample waypoints along a route for navigation export.
 * Navigation apps have URL length limits, so we pick key waypoints.
 */
function sampleWaypoints(
  coords: [number, number][],
  maxPoints: number = 8
): [number, number][] {
  if (coords.length <= maxPoints) return coords

  const step = Math.floor(coords.length / maxPoints)
  const sampled: [number, number][] = []
  for (let i = 0; i < coords.length; i += step) {
    sampled.push(coords[i])
    if (sampled.length >= maxPoints) break
  }
  return sampled
}

/**
 * Generate Apple Maps URL
 * Uses the maps:// scheme which opens Apple Maps on iOS/macOS
 * Falls back to maps.apple.com for web
 */
export function getAppleMapsUrl(route: ScoredRoute): string {
  const coords = route.mapboxRoute.geometry.coordinates
  if (coords.length < 2) return ''

  const start = coords[0]

  // Apple Maps supports dirflg=d (driving) and waypoints via daddr
  // Format: maps://maps.apple.com/?saddr=lat,lng&daddr=lat,lng+to:lat,lng+to:...
  const waypoints = sampleWaypoints(coords, 8)

  // Build the waypoint chain: first waypoint is destination, rest are via points
  // Apple Maps: daddr = wp1+to:wp2+to:wp3+to:...+to:final
  const waypointStr = waypoints
    .slice(1) // skip start (that's saddr)
    .map(([lng, lat]) => `${lat},${lng}`)
    .join('+to:')

  // Use maps.apple.com for universal compatibility (redirects to app on iOS)
  return `https://maps.apple.com/?saddr=${start[1]},${start[0]}&daddr=${waypointStr}&dirflg=d`
}

/**
 * Generate Google Maps URL
 * Uses the maps.google.com/maps/dir/ scheme
 */
export function getGoogleMapsUrl(route: ScoredRoute): string {
  const coords = route.mapboxRoute.geometry.coordinates
  if (coords.length < 2) return ''

  const waypoints = sampleWaypoints(coords, 8)

  // Google Maps: /maps/dir/lat,lng/lat,lng/lat,lng/...
  const pathStr = waypoints
    .map(([lng, lat]) => `${lat},${lng}`)
    .join('/')

  return `https://www.google.com/maps/dir/${pathStr}/@${waypoints[0][1]},${waypoints[0][0]},12z/data=!4m2!4m1!3e0`
}

/**
 * Generate Waze URL
 */
export function getWazeUrl(route: ScoredRoute): string {
  const coords = route.mapboxRoute.geometry.coordinates
  if (coords.length < 2) return ''

  // Waze navigate to a point (supports single destination)
  // For loops, navigate to the farthest waypoint
  const midIdx = Math.floor(coords.length / 2)
  const mid = coords[midIdx]

  return `https://waze.com/ul?ll=${mid[1]},${mid[0]}&navigate=yes`
}

/**
 * Generate GPX file content
 * GPX is the universal format — works with Garmin, Sygic, OsmAnd, etc.
 */
export function generateGpx(route: ScoredRoute): string {
  const coords = route.mapboxRoute.geometry.coordinates
  const name = route.name.replace(/[<>&'"]/g, '')
  const now = new Date().toISOString()

  const trackpoints = coords
    .map(([lng, lat]) => `      <trkpt lat="${lat}" lon="${lng}"></trkpt>`)
    .join('\n')

  // Also add key waypoints for navigation
  const waypoints = sampleWaypoints(coords, 12)
  const waypointXml = waypoints
    .map(([lng, lat], i) => {
      const wpName = i === 0 ? 'Start' : i === waypoints.length - 1 ? 'End' : `WP ${i}`
      return `  <wpt lat="${lat}" lon="${lng}">\n    <name>${wpName}</name>\n  </wpt>`
    })
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Hotfix - Route Like You Mean It"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${name}</name>
    <desc>Generated by Hotfix — ${route.distanceMi} mi, ${route.durationMin} min</desc>
    <time>${now}</time>
  </metadata>
${waypointXml}
  <trk>
    <name>${name}</name>
    <trkseg>
${trackpoints}
    </trkseg>
  </trk>
</gpx>`
}

/**
 * Download GPX file
 */
export function downloadGpx(route: ScoredRoute): void {
  const gpxContent = generateGpx(route)
  const blob = new Blob([gpxContent], { type: 'application/gpx+xml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `hotfix-${route.name.toLowerCase().replace(/\s+/g, '-')}.gpx`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Check if running on iOS (for Apple Maps priority)
 */
export function isIOS(): boolean {
  if (typeof navigator === 'undefined') return false
  return /iPad|iPhone|iPod/.test(navigator.userAgent) ||
    (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)
}
